### PR TITLE
don't descend into our library of math functions

### LINKED ISSUE #30: Jacobian sparsity detection takes a very long time and fails some times
I tried the following and it took a very long time (I had to kill it):
```julia
using SparsityDetection

x = rand(3);
y = similar(x);
f(y, x) = y .= exp.(x);
jacobian_sparsity(f, y, x)
```
Interestingly, `f(y, x) = y .= x .+ 1`, `f(y, x) = y .= x .+ x`, `f(y, x) = y .= x .* x` and `f(y, x) = y .= x .^ 2` all work fine. So it seems that something is going on with `exp`. `log` also fails with some domain error when all the numbers in `x` are positive.

### PR DESCRIPTION
**Pull request by shashi**
fixes #30

### CODE REVIEW

**Comment by shashi** [comment]
thats a lot of really slow CIs.

**Comment by shashi** [comment]
I think `isleaf` should be part of the API.

`isleaf(f) = true` means that if `f` is called with `x<tag>`, then return `f(x)<tag>` instead of trying `f(x<tag>)`.

So if someone has a function like:
```julia
function g(a)
   while a < 1
       a+= rand()
    end
    a
end
```
for whatever reason

and they then want to sparsity detect
```
f(y, x) = y .= g.(x)

```

Then they can set `SparsityDetection.isleaf(::typeof(g)) = true` and it will work.

**Comment by ChrisRackauckas** [comment]
Wouldn't they need to also give you what the sparsity of that function is in the API?

**Comment by shashi** [comment]
Yes, but it can be optional in case of Jacobian. (because you can just say the output depends on all the inputs).. But you're right they would have to say something about it for Hessian.

Well there is a way to say that too `SparsityDetection.linearity`

**Comment by ChrisRackauckas** [comment]
oh it's only for scalar functions?

**Comment by shashi** [comment]
Yeah well that's the easiest thing to provide an API for right away. We currently don't have decent ways of converting sparsity matrix into our metadata (ProvinanceSet or TermCombination although that should be not so hard to do).

Let's hold this thought and if there is a real need for treating sub functions as blackboxes of known sparsity, then we can come back to this idea.

**Pull request merged**
